### ISSUE TITLE
Perhaps tracker should crash/quit/restart when disconnected for a long while?

### ISSUE THREAD

**Issue by reppolice** [ZencashOfficial/nodetracker#41]
Hi,

Impossible for me to say what you guys changed server-side, but my tracker registered "sys" for most of the weekend until I was able to have a look. It was some unable to connect message that I thought would be fixed by restarting the tracker, and indeed it connected immediately upon restart. I don't know how likely it is for such server-side changes to happen in the months and years to come, but if they might produce unsupported and unconnectable configurations, it is an idea to have the tracker terminate and/or restart somehow, for "correct state" to propagate.

**Comment by ADumaine** [comment]
If the tracker loses its connection to one of the servers it should failover to another server and keep trying until it reconnects.  Did the log files for that period show failover attempts?

**Comment by reppolice** [comment]
I will try to back my reminiscences by log sleuthing, but for all I know the tracker was in some undefined state rather in some rotation.

**Comment by ADumaine** [comment]
The most recent installation guides have instructions on how to installing process monitoring to ensure bot zend and the nodetracker are up/restarted when needed.

Closed due to lack of activity.
