### ISSUE TITLE
permanently decomissioning a secure node

### ISSUE THREAD

**Issue by nikmit** [ZencashOfficial/nodetracker#53]
A question to that effect was asked on the forum and I thought @einst had a point. It should be possible to decommission a node and de-register an email address so it no longer is alerted about downtimes.
With the overall number of nodes increasing and earnings falling this will become increasingly necessary.

**Comment by ADumaine** [comment]
Part of this is possible now.  A node operator can run 'node setup' and set the email to 'none' or remove the existing email address, then restart the tracker to update it.  The tracker can then be shut down.

The tracking server will create a Downtime that will continue to get updated until the node is flagged as 'dead' after being 'down' for 5 days then 'inactive' for 5 more days.

The node must remain until all earnings are paid (at least 7 days depending on when payouts are done and when the node was shut down.

**Comment by ADumaine** [comment]
A future feature will be an archive method for older dead nodes.
Closed.
