### ISSUE TITLE
Fuzzy introduction to installation in README.md

### ISSUE THREAD

**Issue by dittaeva** [ZencashOfficial/nodetracker#59]
Under the section "New installation" in README.md, the first paragraph says:

> If you have followed Part 1, Part 2, and Part 2.5, and/or Part 3 of guides for creating a Secure Node, you should be ready to install this on your node.

It is not clear at all which "guides for creating a Secure Node" this is in reference to. There is no such guide in the readme, I can find no such guide in the zen repository, nor anywhere else except for perhaps old entries on blockoperations.com or [zen-solutions.io](https://www.zen-solutions.io/detailed-node-creation-tutorial-part-1/).

It does not make sense to write something like that, and then go on with instructions for how to install. If creating a secure node is not about installing and configuring, then what is it.

**Comment by ADumaine** [comment]
When the beta first started the guides mentioned were the only ones available.  We will get this rewritten/referenced.  Thanks!

**Comment by dittaeva** [comment]
I suppose links to third parties isn't very desirable though.

**Comment by ADumaine** [comment]
Full installation guides have been created and are available at https://zencash.atlassian.net/wiki/spaces/ZEN/pages/7537322/Installation
