### ISSUE TITLE
Exception: existing exception needs to be cleared before changing stake address.

### ISSUE THREAD

**Issue by helsins** [ZencashOfficial/nodetracker#62]
![image](https://user-images.githubusercontent.com/34838187/39960616-9e76c956-5658-11e8-84ab-aea908e6d4d3.png)
Since the exception of "stkdup", I have changed two times stakeaddr, but the exception has always been there.
Every time I change stakeaddr, I restart tracker and be prompted "Exception: existing exception needs to be cleared before changing stake address. see server.", but how can I eliminate this exception before changing stakeaddr?
thank you.

**Comment by PeaStew** [comment]
@ADumaine hi mate, can you answer this one?

**Comment by helsins** [comment]
At first, the Zen on the stakeaddr of my security node is automatically turned to a new Z address (1, the new address is automatically generated by my wallet.  2, and this happens many times before), when the "stkdup" exception appears.

Then I set the new Z address to stakeaddr through "node setup" command, but did not clear the "stkdup" exception. Then I changed the stakeaddr once again, and the exceptions still exist. When I checked log, I found the prompt in the title.

Last night, I turned Zen back to the original stakeaddr and changed back to the original stakeaddr through "node setup" command, but the exception of "stkdup" still exists.

**Comment by PeaStew** [comment]
For clarity, a Z address is a shielded address and cannot be used for staking, I think you mean a T address.

The only reason that the ZEN will be moved to another T address is if you are moving ZEN out from the stake address (for example to move rewards), this is a function of the 'change' behaviour inherited from Bitcoin.

**Comment by asbachb** [comment]
I guess this is a serious bug:

Seems to that you cannot clear the exception without changing the address, but I can't change the address without clearing the exception.

**Comment by votuanphong1983** [comment]
hm..i have the same issue. Now i can not fix this issue too. Please update if you have any new info. Thanks

**Comment by ADumaine** [comment]
This issue was addressed on the tracking servers shortly after being reported.
