### ISSUE TITLE
Issue with EU servers for supernodes

### ISSUE THREAD

**Issue by northdakota** [ZencashOfficial/nodetracker#66]
When tracker trying to register in eu region there are wrong redirect url on server.
see screenshot.
![image](https://user-images.githubusercontent.com/2067100/42565775-1316d44e-850d-11e8-8e9c-9a1f227f0df9.png)

**Comment by ADumaine** [comment]
The redirects shoild be working properly now. Please check and close.

**Comment by ADumaine** [comment]
Closed.  Redirects were fixed.
