### ISSUE TITLE
Tracker use rpcallowip instead of rpcbind for the rpc call ip - doesn't work if tracker and node is not on the same server

### ISSUE THREAD

**Issue by blockmover** [ZencashOfficial/nodetracker#67]
The tracker uses the rpcallowip from zen.conf as the IP address for the rpc call. That works on a single server env but not if separated e.g. docker container env. Tracker need to call the rpcbind IP address from the zen.conf

**Comment by ADumaine** [comment]
It will use rpcbind if rpcallowip is not found.   An alternative is to use the ZENCONF environment variable to set the full path and file name to zen.conf.  See the last section of the README file.  This could be a copy of the the zen.conf modified to work properly,

**Comment by blockmover** [comment]
I had both (rpcbind and rpcallowip) in the file and it didn't work I got a error when the tracker tried to reach the zend server - so I still think it should just take the rpcbind first and if not found then rpcallowip this would allow to have the zend server separated from the tracker. Wdyt?

**Comment by ADumaine** [comment]
There was another node operator that had the issue of using rpcallowip and not rpcbind and it would not work for that situation.   

0.2.1 looked for rpcallowip first, then rpcbind.  
Our installation guide is written with with an `rpcallowip=127.0.0.1`.
Running zend on a another computer was not in the original intention, but I understand making configuration changes may be needed for situation like using containers.
If zen is running on another computer there is no zend.conf local for the tracker set up to find and read.  The rpcbind would never be found.  The rpcbind would only work if set in a local zen.conf with a local ip address.

I think we need to leave it as rpcallowip priority.   

I have the same situation in my development environment where zen is on another computer and used the ZENCONF environment variable on my local system to point to a modified version of zen.conf.  It works fine and allow be to run multiple nodes on different systems for various testing situations.

**Comment by blockmover** [comment]
hmm I see; I implemented a work around so I'm fine now. Maybe the tracker can have an option to set the rpc host ip individually (even just a parameter in the config.json)

**Comment by ADumaine** [comment]
That would have worked in 0.2.1, but in 0.3.0 it was suggested to read the zen.conf file directly on startup instead of saving and maintaining a reflection of it in the tracker config. So 0.3.0 reads zen.conf on startup. The ZENCONF allow you to essentially maintain a separate file for rpc config without having to change config.json.

**Comment by ADumaine** [comment]
Closed due to inactivity.  Please reopen if needed.
