### ISSUE TITLE
One particular SuperNode is shown on several tracker servers (Europe1 & Europe3)

### ISSUE THREAD

**Issue by Gurvynyk** [ZencashOfficial/nodetracker#70]
My supernodes was initially started on Europe1. Then moved to Europe3 Server.. Now 2 of them moved back to Europe1 but visible both on Europe1 and Europe3.  But on Server3 is shown as Down...

I restarted 2 SuperNodes - and they went back to Server Europe3 but on Europe1 they still also visible - but with Down status.

So one SuperNode visible on several Server in one time ?

Moreover on both node detail page ( https://supernodes1.eu.zensystem.io/nodes/772/detail and https://supernodes3.eu.zensystem.io/nodes/772/detail ) for SuperNode Server: home: xns3.eu     current: xns3.eu

**Comment by Gurvynyk** [comment]
![image](https://user-images.githubusercontent.com/23139244/42737750-efbfcb82-8880-11e8-85e5-6c7b83ebefda.png)

**Comment by ADumaine** [comment]
Yes this is a known issue that was being worked on, but your post clarified what was actually taking place.  Thank you.

A fix to properly remove a node from the previous server after moving home servers will be in the next tracking server update.

**Comment by Gurvynyk** [comment]
OK. Just want to be sure that those "down" nodes will not cause exception and no payments.... 

If i have 2 "down" nodes on Europe1 and exact the same nodes (with the same ID) with Up state on Europe3  - can I be sure those 2 down nodes will not null my payments ?

**Comment by ADumaine** [comment]
I you don't see any Exception or Downtime then there is no effect on up time and earnings.
I just restarted supernodes1.eu that cleared the nodes that were stuck there.
