### ISSUE TITLE
Cert check: valid=undefined. ipMatch=undefined  connection issue: ECONNREFUSED

### ISSUE THREAD

**Issue by MetalHelmet** [ZencashOfficial/nodetracker#75]
Updated nodetracker up to 0.3.1 and got issue with cert

Zend (zen-cli getnetworkinfo) says cert is ok and valid 
```$ zen-cli getnetworkinfo
{
  "version": 2001450,
  "subversion": "/zen:2.0.14/",
  "protocolversion": 170002,
  "localservices": "0000000000000001",
  "timeoffset": 0,
  "connections": 9,
  "tls_cert_verified": true,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
```

But node tracker have issue
```
Jul 18 14:24:03 customer node[3626]: 2018-07-18 12:24:03 UTC -- Cert check: valid=undefined. ipMatch=undefined  connection issue: ECONNREFUSED
Jul 18 14:24:03 customer node[3626]: 2018-07-18 12:24:03 UTC -- Cert check: valid=undefined. ipMatch=undefined  connection issue: ECONNREFUSED
Jul 18 14:24:31 customer node[3626]: 2018-07-18 12:24:31 UTC -- Cert check: valid=undefined. ipMatch=undefined  connection issue: ECONNREFUSED

```

![image](https://user-images.githubusercontent.com/41374878/42881127-6036c440-8a9f-11e8-9c5a-21474e574187.png)

**Comment by pssm** [comment]
Had the same, and in my case was the configured 'externalip' IPv6 entry in the zen.conf.

If the address has a left 0 in one of the groups, it will fail, because the 'real' IP address used for comparison won't be the same. Example:

> zen.conf
....
externalip=XXXX:XXXX:XXXX:XXX:XXXX:**01ff**:XXX:XXX
....

Will be seen (externally) as XXXX:XXXX:XXXX:XXX:XXXX:1ff:XXX:XXX.

Quick fix: remove any left-most zeros from the IPv6 entry.

**Comment by MetalHelmet** [comment]
I've done that...
My IPv6 is 2a00:7c80:0:17a::2

Tried to remove :0: - set externalip=2a00:7c80::17b::2
And got error 
`$ Error: Cannot resolve -externalip address: '2a00:7c80::17b::2' `

**Comment by MetalHelmet** [comment]
Still have 
`2018-07-18 16:54:20 UTC -- Cert check: valid=undefined. ipMatch=undefined  connection issue: ECONNREFUSED
2018-07-18 16:54:20 UTC -- Exception: connection issue: ECONNREFUSED
`

I have zen.conf
`externalip=109.236.92.160
externalip=2a00:7c80:0:17b::2`

I have those my IP's usable 
`$ (
> curl ipv4.icanhazip.com
> curl ipv6.icanhazip.com
> )
109.236.92.160
2a00:7c80:0:17b::2
`

Also zen-cli getnetworkinfo says
`$  zen-cli getnetworkinfo
{
  "connections": 8,
  "tls_cert_verified": true,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00000100,
  "localaddresses": [
    {
      "address": "109.236.92.160",
      "port": 9033,
      "score": 4
    },
    {
      "address": "2a00:7c80:0:17b::2",
      "port": 9033,
      "score": 4
    }
  ],
  "warnings": ""
}
`

But node app got error
`2018-07-18 16:56:49 UTC -- Cert check: valid=undefined. ipMatch=undefined  connection issue: ECONNREFUSED
`

All was working fine before update to 0.3.1

**Comment by ADumaine** [comment]
It works on testnet on port 19033 but not on mainnet on 9033.  Check firewall config or port.

**Comment by MetalHelmet** [comment]
Can I ask what do you mean "works on testnet on port 19033 but not on mainnet on 9033" ?

**Comment by ADumaine** [comment]
I am able to do the same test from my development system that the servers use.  Your node is replying on port 19033 on testnet and gets the connection refused when I try it on mainnet at port 9033. The node is on testnet.

**Comment by ADumaine** [comment]
Closed. Assumed working properly now.  Please reopen if needed.
