### ISSUE TITLE
Frequent dns: DNS configuration issue exceptions

### ISSUE THREAD

**Issue by MetalHelmet** [ZencashOfficial/nodetracker#77]
Why supernodes constantly gets such exception - dns . Exception gets closed after some time by itself...

![image](https://user-images.githubusercontent.com/41374878/42953699-ac01d772-8b83-11e8-85ff-f0bc63a1b09d.png)

**Comment by ADumaine** [comment]
This was an issue with the tracking server anti-spoofing settings which have were changes shortly after this ticket was opened.
