### ISSUE TITLE
Help: Challenge failed, reason is "Witness for note commitment is null"

### ISSUE THREAD

**Issue by helsins** [ZencashOfficial/nodetracker#80]
Cert check is valid, balance is enough, stat check is valid, but challenge failed.
I don't know what to do.

![witness1](https://user-images.githubusercontent.com/34838187/44310835-70478480-a40f-11e8-9478-377fd843be07.JPG)
![witness2](https://user-images.githubusercontent.com/34838187/44310849-af75d580-a40f-11e8-8f02-07915cf7271a.JPG)

**Comment by helsins** [comment]
@ADumaine @FranckDG @Shambou help help help，，，thanks thanks thanks，，，

**Comment by ADumaine** [comment]
@helsins  This is an issue with the wallet, address, or blockchain.  It might be solved by stopping and restarting zend with a -reindex.

I suggest you open a ticket in our support system at https://support.horizen.global.
