### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lookfirst** [ZencashOfficial/nodetracker#86]
In order to get better up to speed on the implementation of the nodetracker, I have been reviewing the discussions that I could find online.

Here are some links that I have found:

* @ADumaine is `devman` in slack and discourse forums.
* https://blog.zencash.com/secure-node-tracking-and-payment-system-project-manager-selected/
* https://forum.horizen.global/t/secure-node-tracking-and-payment-system-software-development-project-discussion/126/42
* https://docs.google.com/document/d/1q18j-OmYCCYzmCK-fmsmOmL25hfuIgo_7WTngaNgMKQ/edit

**Comment by ADumaine** [comment]
This has been intentionally left open for informational purposes.

Documentation on Secure and Super nodes can be found here" https://horizenofficial.atlassian.net/wiki/spaces/ZEN/pages/136872141/Secure+and+Super+Nodes

**Comment by lookfirst** [comment]
What is the future of nodetracker?

**Comment by ADumaine** [comment]
It has a limited life span.  The current version of nodetracker will be used until the tracking and payment system is rebuilt on a side chain.  This may be late 2019 or early 2020 TBD.

**Comment by zennermac** [comment]
A link to the wiki as mentioned in this issue is being added to the README.md for reference
https://horizenofficial.atlassian.net/wiki/spaces/ZEN/pages/136872141/Secure+and+Super+Nodes
