### ISSUE TITLE
Parameter for skipping prompts in setup.js

### ISSUE THREAD

**Issue by DatDraggy** [ZencashOfficial/nodetracker#87]
I think it would be helpful to be able to just skip all prompts, if there is a default config, and only prompt for new settings if a new version was downloaded. Speeds things up and also reduces the amount of errors that could happen because of typos or something like that.

**Comment by northdakota** [comment]
I think it's good idea to add possibility to use parameters as `--type=secure --stake=xxxx` and so on
I have a lot of nodes and all my processes are automated to run on multiple nodes. But there are problems currently with upgrade.

**Comment by hito** [comment]
Sensible defaults should be a secure node for the type, and for the category the host.

**Comment by ADumaine** [comment]
A feature request has been created in our internal software project manager.
Thanks for the suggestion!
